name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main # Adjust if your default branch is different

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest' # or specify a version, e.g. '1.0.0'
      
      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
